// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5q-Ml2OlC-CH7DbuQafi_mOM479PPx5c',
    appId: '1:1096100484299:web:8e18962637eb7e8403f74e',
    messagingSenderId: '1096100484299',
    projectId: 'flutter-5bfa',
    authDomain: 'flutter-5bfa.firebaseapp.com',
    storageBucket: 'flutter-5bfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByM5iTlyo6BLMW-2BQbMxB7sPuT-RsrdU',
    appId: '1:1096100484299:android:8d48384063b0bd3703f74e',
    messagingSenderId: '1096100484299',
    projectId: 'flutter-5bfa',
    storageBucket: 'flutter-5bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0fQAJytpnp3wzwIxWYiEQD_d0OcINdc',
    appId: '1:1096100484299:ios:28913382ae4c4a3303f74e',
    messagingSenderId: '1096100484299',
    projectId: 'flutter-5bfa',
    storageBucket: 'flutter-5bfa.firebasestorage.app',
    iosBundleId: 'com.mifirebase.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0fQAJytpnp3wzwIxWYiEQD_d0OcINdc',
    appId: '1:1096100484299:ios:28913382ae4c4a3303f74e',
    messagingSenderId: '1096100484299',
    projectId: 'flutter-5bfa',
    storageBucket: 'flutter-5bfa.firebasestorage.app',
    iosBundleId: 'com.mifirebase.appfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5q-Ml2OlC-CH7DbuQafi_mOM479PPx5c',
    appId: '1:1096100484299:web:341406a7adcf23d203f74e',
    messagingSenderId: '1096100484299',
    projectId: 'flutter-5bfa',
    authDomain: 'flutter-5bfa.firebaseapp.com',
    storageBucket: 'flutter-5bfa.firebasestorage.app',
  );
}
